### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by SGrondin** [vbmithr/ocaml-websocket#19]
Hi,

I'd love to use your package as part of an application I'm currently writing that makes heavy use of Async and Cohttp. Is there any plan to add Async support the same way that Cohttp does by abstracting away the logic and offering both Lwt and Async as options?

Thanks

**Comment by vbmithr** [comment]
I should start working on this soon. I need to abstract the library both from the monadic concurrency library (Lwt/Async) and the SSL handling (ocaml-tls/async_ssl).

**Comment by rgrinberg** [comment]
Can you accomplish the latter by using conduit?

**Comment by vbmithr** [comment]
On 23/05/2015 21:28, Rudi Grinberg wrote:
> Can you accomplish the latter by using conduit?

Good question. And good idea too :)

-- 
Vincent

**Comment by hhugo** [comment]
:+1:

**Comment by vbmithr** [comment]
Initial async support (client) has been pushed to master. I'm gonna use the client part, so I'm gonna test mostly this. Server has not been tested yet.

**Comment by copy** [comment]
One code question: In [line 175 and 176](https://github.com/vbmithr/ocaml-websocket/blob/master/lib/websocket_async.ml#L175-L176) we create a `Reader` and `Writer` from pipes. Wouldn't it be more efficient to accept `Reader` and `Writer`, since this is also what `Tcp.Server.create` provides?

By the way, I'm using the server in a small project and it works (even though the interface is a bit crude).

**Comment by vbmithr** [comment]
Ah that's good news that the server works, it's so rare that something works without being tested (especially when it's me writing the code).

As for your question, I don't remember why I did it like this and it was not AFAIR a question of efficiency. If you manage to patch this to something equivalent with a simpler interface, I'll take it :)

**Comment by vbmithr** [comment]
We now have client and server async support. Closing this.
