### ISSUE TITLE
ocaml version compatibility

### ISSUE THREAD

**Issue by andrewray** [vbmithr/ocaml-websocket#22]
Is `>= 4.02` a constraint you intend for websocket going forward?

**Comment by vbmithr** [comment]
I'm not sure I understand the sentence. If you mean if I intend to always request the latest version of OCaml to use websockets, no. It's just that this current version uses the lwt ppx syntax, hence needs >= 4.02. Do you need backward compatibility ?

**Comment by andrewray** [comment]
Ah, I see; Ppx requires 4.02 or greater.  I was asking because `iocaml` used to be compatible with all 4.x series compilers until this constraint, but it is reasonable.  I'll just keep an older iocaml package working for those compilers.

**Comment by vbmithr** [comment]
Yeah, I'm not really a backward-compatibility kind of person. It frustrates me to have cool new features around and not allowing myself to use them because I want to preserve backward compatibility. You can probably use the former release for your older iocaml version, it should probably work well too.
